// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYZQlLuqIX38QoLcKuwXOMG6i_dOVlz2s',
    appId: '1:265192025359:web:ca06f532e0fd76fa2fe27a',
    messagingSenderId: '265192025359',
    projectId: 'final-challenge-seanwho',
    authDomain: 'final-challenge-seanwho.firebaseapp.com',
    storageBucket: 'final-challenge-seanwho.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0epQh7PFNUsuv8qw8AxqmqG7uBvMvW-8',
    appId: '1:265192025359:android:b9ae12d2d95188d72fe27a',
    messagingSenderId: '265192025359',
    projectId: 'final-challenge-seanwho',
    storageBucket: 'final-challenge-seanwho.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnYwB7eoTLXj79BIwO0NDwU7mb4xhwCYM',
    appId: '1:265192025359:ios:655330eb08eb15b22fe27a',
    messagingSenderId: '265192025359',
    projectId: 'final-challenge-seanwho',
    storageBucket: 'final-challenge-seanwho.appspot.com',
    iosBundleId: 'com.example.finalChallenge',
  );
}
